name: Rust Audit Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cargo_audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install cargo-audit
      run: cargo install cargo-audit

    - name: Search and Audit Cargo Projects
      run: |
        audit_failures=0
        for cargo_toml in $(find . -name 'Cargo.toml'); do
          dir=$(dirname $cargo_toml)
          echo "Running cargo audit in $dir"
          (cd $dir && cargo generate-lockfile && cargo audit) || {
            echo "Vulnerabilities found in $dir"
            audit_failures=$((audit_failures+1))
          }
        done
        echo "Cargo audit completed with $audit_failures project(s) having vulnerabilities."
        if [ $audit_failures -ne 0 ]; then
          echo "Please review the vulnerabilities reported above."
          # Optional: exit with success to not fail the pipeline
           exit 0
        fi
