name: Rust Audit Check

on:
  pull_request:
    branches: [ main ]

jobs:
  cargo_audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run cargo audit check
      uses: actions-rs/audit-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
